# Generated by Django 4.0.2 on 2022-02-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter author's name", max_length=100, verbose_name='Author name')),
                ('last_name', models.CharField(help_text="Enter author's surname", max_length=100, verbose_name='Author surname')),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter date of death', null=True, verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter book title', max_length=200, verbose_name='Book title')),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000, verbose_name='Book annotation')),
                ('isbn', models.CharField(help_text='Must contain 13 characters', max_length=13, verbose_name='ISBN of the book')),
                ('author', models.ManyToManyField(help_text='Choose book author', null=True, to='catalog.Author', verbose_name='Book author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter book genre', max_length=200, verbose_name='Book genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter language', max_length=20, verbose_name='Book language')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter book status', max_length=20, verbose_name='Book instance status')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Enter book instance inventory number', max_length=20, null=True, verbose_name='Inventory number')),
                ('imprint', models.CharField(help_text='Enter publisher and year of publication', max_length=200, verbose_name='Publisher')),
                ('due_back', models.DateField(blank=True, help_text='Enter order status term', null=True, verbose_name='Status end date')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Change instance status', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Book instance status')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Choose book genre', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Book genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Choose book language', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Book language'),
        ),
    ]
