# Generated by Django 4.0.2 on 2022-02-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Choose book author', to='catalog.Author', verbose_name='Book author'),
        ),
    ]
