# Generated by Django 4.0.2 on 2022-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Enter date of death', null=True, verbose_name='Date of death'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter date of birth', null=True, verbose_name='Date of birth'),
        ),
    ]
